# アクション名
name: Test

# タイミングを指定
on:
    pull_request:
        branches: [main]

jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: yarn install
              run: yarn install
            - name: Run Test
              run: yarn test
            - name: Upload test coverage artifact
              uses: actions/upload-artifact@v1
              with:
                  name: coverage
                  path: coverage_dir
