/**
 * Regenerates the "Function List" section of README.md from typedoc output.
 * Walks src/<Module> exports and links each symbol to its GitHub Wiki page
 * generated by typedoc-github-wiki-theme.
 */

// biome-ignore lint/correctness/noNodejsModules: node:path has no Bun equivalent
import { dirname, join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const SRC = join(ROOT, "src");
const DOC = join(ROOT, "doc");
const README = join(ROOT, "README.md");
const WIKI = "https://github.com/riya-amemiya/UMT/wiki";
const SKIP = new Set(["types", "tests"]);
// Earlier kinds win when the same symbol name maps to multiple typedoc files.
const KINDS = [
  "Function",
  "Class",
  "Variable",
  "Interface",
  "TypeAlias",
  "Enum",
];

const STAR = /export\s+\*\s+from\s+["']([^"']+)["']/g;
const NAMED = /export\s*\{([^}]+)\}(?:\s*from\s*["'][^"']+["'])?/g;
const DECL =
  /^export\s+(?:declare\s+|async\s+|abstract\s+)*(?:const|let|var|function\*?|class|interface|type|enum)\s+([A-Za-z_$][\w$]*)/gm;
const ID = /^[A-Za-z_$][\w$]*$/;
const cmp = (a: string, b: string) =>
  a.localeCompare(b, "en", { sensitivity: "base" });

const resolveTs = async (
  from: string,
  spec: string,
): Promise<string | null> => {
  const t = resolve(dirname(from), spec);
  const [asIndex, asFile] = await Promise.all([
    Bun.file(`${t}/index.ts`).exists(),
    Bun.file(`${t}.ts`).exists(),
  ]);
  if (asIndex) {
    return `${t}/index.ts`;
  }
  if (asFile) {
    return `${t}.ts`;
  }
  return null;
};

const collect = async (
  file: string,
  seen = new Set<string>(),
): Promise<Set<string>> => {
  const names = new Set<string>();
  if (seen.has(file)) {
    return names;
  }
  seen.add(file);
  const src = await Bun.file(file).text();

  const stars = [...src.matchAll(STAR)].map(([, spec]) => spec);
  const resolved = await Promise.all(stars.map((s) => resolveTs(file, s)));
  const sub = await Promise.all(
    resolved
      .filter((f): f is string => f !== null)
      .map((f) => collect(f, seen)),
  );
  for (const set of sub) {
    for (const n of set) {
      names.add(n);
    }
  }
  for (const [, list] of src.matchAll(NAMED)) {
    for (const part of list.split(",")) {
      const n = part
        .trim()
        .replace(/^type\s+/, "")
        .replace(/^\S+\s+as\s+/, "");
      if (ID.test(n)) {
        names.add(n);
      }
    }
  }
  for (const [, n] of src.matchAll(DECL)) {
    names.add(n);
  }
  return names;
};

const buildKindMap = async (): Promise<Map<string, string>> => {
  const map = new Map<string, string>();
  for await (const file of new Bun.Glob("*.md").scan({ cwd: DOC })) {
    const dot = file.indexOf(".");
    const kind = file.slice(0, dot);
    const name = file.slice(dot + 1, -3);
    if (!KINDS.includes(kind)) {
      continue;
    }
    const cur = map.get(name);
    if (!cur || KINDS.indexOf(kind) < KINDS.indexOf(cur)) {
      map.set(name, kind);
    }
  }
  return map;
};

const listModules = async (): Promise<string[]> => {
  const modules: string[] = [];
  for await (const dir of new Bun.Glob("*/index.ts").scan({ cwd: SRC })) {
    const name = dir.split("/")[0];
    if (!SKIP.has(name)) {
      modules.push(name);
    }
  }
  return modules.sort(cmp);
};

const generate = async (): Promise<string> => {
  const [kinds, modules] = await Promise.all([buildKindMap(), listModules()]);
  const sections = await Promise.all(
    modules.map(async (mod) => {
      const names = [...(await collect(join(SRC, mod, "index.ts")))]
        .filter((n) => kinds.has(n))
        .sort(cmp);
      if (names.length === 0) {
        return null;
      }
      const lines = [`### ${mod}`, ""];
      for (const n of names) {
        lines.push(
          `- [${n}](${WIKI}/${kinds.get(n)}.${encodeURIComponent(n)})`,
        );
      }
      lines.push("");
      return lines;
    }),
  );
  const out = ["## Function List", ""];
  for (const section of sections) {
    if (section) {
      out.push(...section);
    }
  }
  return `${out.join("\n").trimEnd()}\n`;
};

await Bun.$`bunx typedoc`.cwd(ROOT);
const list = await generate();
const readme = await Bun.file(README).text();
const idx = readme.indexOf("## Function List");
const head = idx === -1 ? readme : readme.slice(0, idx);
await Bun.write(README, `${head.trimEnd()}\n\n${list}`);
console.log(`Updated ${README}`);
