use super::Value;
use std::collections::HashMap;

/// Creates an object composed of keys generated from the results of running each element of collection through iteratee.
///
/// # Arguments
///
/// * `collection` - The collection to iterate over (as a slice)
/// * `iteratee` - A function that takes a value and returns a key
///
/// # Returns
///
/// A HashMap with keys generated by the iteratee function.
///
/// # Examples
///
/// ```
/// use umt_rust::object::{umt_key_by, Value};
///
/// let items = vec![
///     Value::Object({
///         let mut m = std::collections::HashMap::new();
///         m.insert("id".to_string(), Value::String("a".to_string()));
///         m.insert("name".to_string(), Value::String("Alice".to_string()));
///         m
///     }),
///     Value::Object({
///         let mut m = std::collections::HashMap::new();
///         m.insert("id".to_string(), Value::String("b".to_string()));
///         m.insert("name".to_string(), Value::String("Bob".to_string()));
///         m
///     }),
/// ];
///
/// let result = umt_key_by(&items, |v| {
///     if let Value::Object(obj) = v {
///         if let Some(Value::String(id)) = obj.get("id") {
///             return id.clone();
///         }
///     }
///     String::new()
/// });
///
/// assert!(result.contains_key("a"));
/// assert!(result.contains_key("b"));
/// ```
pub fn umt_key_by<F>(collection: &[Value], iteratee: F) -> HashMap<String, Value>
where
    F: Fn(&Value) -> String,
{
    let mut result = HashMap::new();

    for value in collection {
        let key = iteratee(value);
        result.insert(key, value.clone());
    }

    result
}

/// Creates an object composed of keys generated by extracting a property from each element.
///
/// # Arguments
///
/// * `collection` - The collection to iterate over
/// * `property` - The property name to use as the key
///
/// # Returns
///
/// A HashMap with keys extracted from the specified property.
///
/// # Examples
///
/// ```
/// use umt_rust::object::{umt_key_by_property, Value};
///
/// let items = vec![
///     Value::Object({
///         let mut m = std::collections::HashMap::new();
///         m.insert("id".to_string(), Value::String("a".to_string()));
///         m.insert("name".to_string(), Value::String("Alice".to_string()));
///         m
///     }),
///     Value::Object({
///         let mut m = std::collections::HashMap::new();
///         m.insert("id".to_string(), Value::String("b".to_string()));
///         m.insert("name".to_string(), Value::String("Bob".to_string()));
///         m
///     }),
/// ];
///
/// let result = umt_key_by_property(&items, "id");
///
/// assert!(result.contains_key("a"));
/// assert!(result.contains_key("b"));
/// ```
pub fn umt_key_by_property(collection: &[Value], property: &str) -> HashMap<String, Value> {
    umt_key_by(collection, |v| {
        if let Value::Object(obj) = v {
            if let Some(val) = obj.get(property) {
                return value_to_string(val);
            }
        }
        String::new()
    })
}

/// Helper function to convert a Value to a string for use as a key.
fn value_to_string(value: &Value) -> String {
    match value {
        Value::String(s) => s.clone(),
        Value::Int(i) => i.to_string(),
        Value::Float(f) => f.to_string(),
        Value::Bool(b) => b.to_string(),
        _ => String::new(),
    }
}
