"""
Time constants in milliseconds.
"""

ONE_SECOND_MS = 1000
ONE_MINUTE_MS = ONE_SECOND_MS * 60
ONE_HOUR_MS = ONE_MINUTE_MS * 60
ONE_DAY_MS = ONE_HOUR_MS * 24
ONE_WEEK_MS = ONE_DAY_MS * 7
ONE_MONTH_MS_28 = ONE_DAY_MS * 28
ONE_MONTH_MS_29 = ONE_DAY_MS * 29
ONE_MONTH_MS = ONE_DAY_MS * 30
ONE_MONTH_MS_31 = ONE_DAY_MS * 31
ONE_YEAR_MS = ONE_DAY_MS * 365
ONE_YEAR_MS_366 = ONE_DAY_MS * 366
