export * from "./isArray";
export * from "./isBrowser";
export * from "./isDouble";
export * from "./isNode";
export * from "./isNodeWebkit";
export * from "./isNotEmpty";
export * from "./isNumber";
export * from "./isObject";
export * from "./isPrimeNumber";
