name: Auto Assign PR Creator

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    name: Auto assign PR creator
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Auto assign PR creator
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_CREATOR: ${{ github.event.pull_request.user.login }}
          GITHUB_REPO: ${{ github.repository }}
        run: |
          gh pr edit "$PR_NUMBER" --add-assignee "$PR_CREATOR" --repo "$GITHUB_REPO"