name: Build and deploy website

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x
            - name: Install NPM packages
              run: npm install -g yarn && yarn
            - name: Build website
              run: yarn build && yarn typedoc
            - name: Deploy website
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: doc
