name: Main Package CI (Node.js)
on:
  pull_request:
    branches:
      - main
      - feature/*
    paths:
      - 'package/main/**'
      - '.github/workflows/main-package-node.yml'
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'package/main/**'
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  test:
    name: Run Tests (Node.js)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x, 26.x]
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./package/main
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Nix
        uses: DeterminateSystems/determinate-nix-action@d96678350ffd6a456235832eb11e1c491589b7bb # v3.21.8
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # 7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore Dependencies Cache
        id: cache-restore-dev-depends
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: '**/node_modules'
          key: dev-depends-${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package/main/bun.lock') }}
      - name: Install Dependencies
        if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        run: nix develop -c bun i
      - name: Run Tests with Coverage
        run: npx jest --coverage
      - name: Save Dependencies Cache
        if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        id: cache-save-dev-depends
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: '**/node_modules'
          key: dev-depends-${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package/main/bun.lock') }}
