# アクション名
name: Main Package Test

# タイミングを指定
on:
    pull_request:
        paths:
            - 'package/main/src/**'
    workflow_dispatch:

jobs:
    javascriptCheck:
        name: JavaScript Check on Ubuntu
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: actions/cache@v3
              with:
                  enableCrossOsArchive: true
                  path: |
                    ${YARN_CACHE_FOLDER}
                  key: ${{ runner.os }}-yarn-cache-v1
            - run: yarn
            - name: Run check
              run: yarn lint
    javascriptTest:
        name: JavaScript Test on Ubuntu
        needs: javascriptCheck
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18.x, 20.x]
            shard: [1/4, 2/4, 3/4, 4/4]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: yarn install
              run: yarn
            - name: Run Build
              run: yarn build
            - uses: actions/cache@v3
              with:
                  enableCrossOsArchive: true
                  path: |
                    module
                  key: ${{ runner.os }}-${{ matrix.node-version }}-${{ matrix.shard }}-${{ github.sha }}
            - name: Run Test ${{ matrix.shard }}
              run: yarn test --shard ${{ matrix.shard }}