# アクション名
name: Main Package Test

# タイミングを指定
on:
    pull_request:
        paths:
            - 'package/main/src/**'
            - 'tests/**'
            - '.github/workflows/**'
    workflow_dispatch:

jobs:
    javascriptSetup:
        name: JavaScript Check on Ubuntu
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [0.8.1]
                os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-node${{ matrix.bun-version }}-${{ hashFiles('package.json') }}
            - name: Install dependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              run: bun i
            - name: Cache Save devDependencies
              if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
              id: cache-save-dev-depends
              uses: actions/cache/save@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-node${{ matrix.bun-version }}-${{ hashFiles('package.json') }}
    javascriptLint:
        name: JavaScript Lint on Ubuntu
        needs: javascriptSetup
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                bun-version: [0.8.1]
                os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-node${{ matrix.bun-version }}-${{ hashFiles('package.json') }}
            - name: Lint
              run: bun run lint

    javascriptBuild:
          name: JavaScript Build on Ubuntu
          needs: javascriptSetup
          runs-on: ${{ matrix.os }}
          strategy:
              matrix:
                  bun-version: [0.8.1]
                  os: [ubuntu-latest]
          defaults:
            run:
              working-directory: ./package/main
          steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-node${{ matrix.bun-version }}-${{ hashFiles('package.json') }}
            - uses: actions/cache/restore@v3
              id: cache-restore-prod
              with:
                  enableCrossOsArchive: true
                  path: '**/module'
                  key: ${{ matrix.bun-version }}-${{ github.sha }}-${{ hashFiles('module/index.js') }}
            - name: Build
              if: steps.cache-restore-prod.outputs.cache-hit != 'true'
              run: bun run build
            - run: ls module
            - name: Cache Save Build
              if: steps.cache-restore-prod.outputs.cache-hit != 'true'
              uses: actions/cache/save@v3
              with:
                  enableCrossOsArchive: true
                  path: '**/module'
                  key: ${{ matrix.bun-version }}-${{ github.sha }}-${{ hashFiles('module/index.js') }}

    javascriptTest:
        name: JavaScript Test on Ubuntu
        needs: javascriptBuild
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            bun-version: [0.8.1]
            shard: [1/4, 2/4, 3/4, 4/4]
            os: [ubuntu-latest]
        defaults:
          run:
            working-directory: ./package/main
        steps:
            - uses: actions/checkout@v3
            - name: Use Bun ${{ matrix.bun-version }}
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: ${{ matrix.bun-version }}
            - name: Cache Restore productionDependencies
              uses: actions/cache/restore@v3
              with:
                  path: '**/node_modules'
                  key: dev-depends-${{ matrix.os }}-node${{ matrix.bun-version }}-${{ hashFiles('package.json') }}
            - uses: actions/cache/restore@v3
              id: cache-restore-prod
              with:
                  enableCrossOsArchive: true
                  path: '**/module'
                  key: ${{ matrix.bun-version }}-${{ github.sha }}-${{ hashFiles('module/index.js') }}
            - name: Run Test ${{ matrix.shard }}
              run: bun run test --shard ${{ matrix.shard }}
            - name: Cache Save Build
              if: steps.cache-restore-prod.outputs.cache-hit != 'true'
              uses: actions/cache/save@v3
              with:
                  enableCrossOsArchive: true
                  path: '**/module'
                  key: ${{ matrix.bun-version }}-${{ github.sha }}