name: Main Package CI (Benchmark)
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      runBenchmarkName:
        type: choice
        required: true
        options:
          - chunk
          - sort
jobs:
  setup:
    name: Setup Dependencies
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./package/main
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Nix
        uses: DeterminateSystems/determinate-nix-action@9adf02b41cfdac2632e1c16f0480ff5bf3b05dd6 # v3.21.1
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Restore Dependencies Cache
        id: cache-restore-dev-depends
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: '**/node_modules'
          key: dev-depends-${{ matrix.os }}-bun-${{ hashFiles('package/main/bun.lock') }}
      - name: Install Dependencies
        if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        run: nix develop -c bun i
      - name: Save Dependencies Cache
        if: steps.cache-restore-dev-depends.outputs.cache-hit != 'true'
        id: cache-save-dev-depends
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: '**/node_modules'
          key: dev-depends-${{ matrix.os }}-bun-${{ hashFiles('package/main/bun.lock') }}
  benchmark:
    name: Run Benchmark
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./package/main
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup Nix
        uses: DeterminateSystems/determinate-nix-action@9adf02b41cfdac2632e1c16f0480ff5bf3b05dd6 # v3.21.1
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Restore Dependencies Cache
        id: cache-restore-dev-depends
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: '**/node_modules'
          key: dev-depends-${{ matrix.os }}-bun-${{ hashFiles('package/main/bun.lock') }}
      - name: Run Benchmark ${{ github.event.inputs.runBenchmarkName }}
        run: nix develop -c bun run ./src/tests/benchmark/${{ github.event.inputs.runBenchmarkName }}.ts
