name: Node Plugin CI
permissions:
  contents: read

on:
    pull_request:
      branches:
        - main
        - develop
        - feature/*
      paths:
        - 'package/umt_plugin_node/src/**'
    workflow_dispatch:

jobs:
    ci:
        name: Node Plugin CI
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [20.x]
        defaults:
          run:
            working-directory: ./package/umt_plugin_node
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # 6.0.0
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: yarn
            - name: Build Package
              run: yarn build
            - name: Run Tests
              run: yarn test