name: Publish Main Package to npm
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    name: Publish umt packages
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'main-')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./package/main
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Nix
        uses: DeterminateSystems/determinate-nix-action@527f17dd63d2d60d3e5552934bc84b9a33a14d11 # v3.22.2
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Setup Node.js for npm publish
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies with frozen lockfile
        run: nix develop -c bun install --frozen-lockfile
      - name: Build project
        run: nix develop -c bun run build:clean
      - name: Lint
        run: nix develop -c bun run lint:ci
      - name: Test
        run: nix develop -c bun run test
      - name: Remove unnecessary build artifacts for accurate size measurement
        run: rm -rf module/tsconfig.tsbuildinfo module/tests
      - name: Publish umt to npm
        run: npm publish --provenance
