name: Publish Main Package to npm
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publish:
    name: Publish umt packages
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'main-')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ./package/main
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Nix
        uses: DeterminateSystems/determinate-nix-action@c70cb8ae92d68c66953db28a26a63db1665bc837 # v3.21.5
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Setup Node.js for npm publish
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies with frozen lockfile
        run: nix develop -c bun install --frozen-lockfile
      - name: Build project
        run: nix develop -c bun run build:clean
      - name: Lint
        run: nix develop -c bun run lint:ci
      - name: Test
        run: nix develop -c bun run test
      - name: Remove unnecessary build artifacts for accurate size measurement
        run: rm -rf module/tsconfig.tsbuildinfo module/tests
      - name: Publish umt to npm
        run: npm publish --provenance
