name: Python Package CI
on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
    paths:
      - 'package/umt_python/**'
      - '.github/workflows/python-package-ci.yml'
  workflow_dispatch:
permissions:
  pull-requests: write
jobs:
  format:
    name: Run Format Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./package/umt_python
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Run Format Check
        run: make format
  lint:
    name: Run Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./package/umt_python
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Run Lint
        run: make lint
  typecheck:
    name: Run Type Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./package/umt_python
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Run Type Check
        run: make typecheck
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./package/umt_python
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: make test
