# アクション名
name: UMT Node Plugin Package Test

# タイミングを指定
on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: UMT Node Plugin Package Test on Ubuntu
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [16.x]
        defaults:
          run:
            working-directory: ./package/umt_plugin_node
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: yarn install
              run: yarn
            - name: Run Build
              run: yarn build
            - name: Run Test
              run: yarn test