# アクション名
name: UMT Wasm Plugin Package Test

# タイミングを指定
on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_cache:
        name: UMT Wasm Plugin Package Build on Ubuntu
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./package/umtn_wasm
        steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/cache_cargo
        - name: build
          run: cargo build
    test:
      name: UMT Wasm Plugin Package Test on Ubuntu
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./package/umtn_wasm
      steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache_cargo
      - name: test
        run: cargo test --all -- --nocapture
      needs: build_cache