# アクション名
name: UMT Wasm Plugin Package Test

# タイミングを指定
on:
    pull_request:
        paths:
            - 'package/umt_plugin_wasm/src/**'

jobs:
    build:
        name: UMT Wasm Plugin Package Test on Ubuntu
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./package/umt_plugin_wasm
        steps:
            - uses: actions/checkout@v3
            - uses: actions-rs/cargo@v1
              with:
                command: test