name: Wasm Plugin CI
permissions:
  contents: read
on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
    paths:
      - 'package/umt_wasm/**'
      - '.github/workflows/wasm-plugin-ci.yml'
  workflow_dispatch:
jobs:
  format:
    name: Check Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package/umt_wasm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Check Format
        run: cargo fmt --check
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package/umt_wasm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy -- -D warnings
  build:
    name: Build Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package/umt_wasm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build Package
        run: cargo build
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./package/umt_wasm
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@nightly
      - name: Setup Nix
        uses: DeterminateSystems/determinate-nix-action@629b284231c2a82554b724e357e47fc6020833c8 # v3.21.2
      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
      - name: Run Tests(Cargo)
        run: cargo test --all -- --nocapture
